apiVersion: v1
kind: Secret
metadata:
  name: container-registry
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ewogICAgICAgICJhdXRocyI6IHsgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAidGVtcGVzdHVkb3MuYXp1cmVjci5pbyI6IHsKICAgICAgICAgICAgICAgICAgICAgICAgImF1dGgiOiAiZEdWdGNHVnpkSFZrYjNNNllrTmxaRzVWVmpsb0syeFdaRVE0T1RCTFFUSk9PVVZaTVRORmFrZzNOVE09IgogICAgICAgICAgICAgICAgfQogICAgICAgIH0KfSU=