version: '3.4'

networks:
  demo:
    driver: bridge
    
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - 15672:15672
      - 5672:5672
    networks:
      - demo

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2017-CU20-ubuntu-16.04
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=123@Mudar
    ports:
      - 1433:1433
    networks:
      - demo

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123Mudar