apiVersion: v1
kind: Secret
metadata:
  name: container-registry
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CgkJCSJhdXRoIjogImJHVmhibVJ5YjJGc2RtVnpPRFk2YkdVdU1USTJPVGcyWHlzPSIKCQl9LAoJCSJ0ZW1wZXN0dWRvcy5henVyZWNyLmlvIjogewoJCQkiYXV0aCI6ICJkR1Z0Y0dWemRIVmtiM002WWtObFpHNVZWamxvSzJ4V1pFUTRPVEJMUVRKT09VVlpNVE5GYWtnM05UTT0iCgkJfQoJfQp9