receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:
    timeout: 10s

exporters:
  logging:
    logLevel: debug

  zipkin:
    endpoint: "http://zipkin:9411/api/v2/spans"

  otlp/elastic:
    endpoint: apm-server:8200
    insecure: true

  jaeger:
    endpoint: jaeger:14250
    insecure: true

extensions:
  health_check:

service:
  extensions: [health_check]

  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, zipkin, otlp/elastic, jaeger]

    metrics:
      receivers: [otlp]
      exporters: [logging, otlp/elastic]

    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/elastic]
