version: '3.4'

networks:
  mservices:
    driver: bridge
  otel-collector:
    driver: bridge
  elk:
    driver: bridge
  apm:
    driver: bridge
  others:
    driver: bridge
    

services:
  entrypoint:
    image: lele-sevico-exemplo:v1.0.0
    container_name: entrypoint
    build:
      context: ./AspNet
      dockerfile: Dockerfile
    ports:
      - 8080:5000
    environment:
      - Options__ServiceName=Entrypoint
      - Options__Mode=CLIENT
      - Options__MaxDelayMileseconds=800
      - Options__UrlClient=http://servico-core-a:5000
      - Options__OtelUrl=http://collector:4317
    networks:
      - mservices
      - otel-collector

  servico-core-a:
    image: lele-sevico-exemplo:v1.0.0
    container_name: servico_core_a
    environment:
      - Options__ServiceName=Servico_A
      - Options__Mode=CLIENT
      - Options__MaxDelayMileseconds=1800
      - Options__UrlClient=http://servico-core-b:5000
      - Options__OtelUrl=http://collector:4317
    networks:
      - mservices
      - otel-collector

  servico-core-b:
    image: lele-sevico-exemplo:v1.0.0
    container_name: servico_core_b
    environment:
      - Options__ServiceName=Servico_B
      - Options__Mode=SERVER
      - Options__MaxDelayMileseconds=1200
      - Options__OtelUrl=http://collector:4317
      - Options__Seed__Records=10
      - Options__Seed__MaxBodyWords=100
    networks:
      - mservices
      - otel-collector

  collector:
    image: otel/opentelemetry-collector-contrib:0.23.0
    container_name: collector
    command: [ "--config=/etc/otel-collector-config.yml" ]
    volumes:
      - ./config.yaml:/etc/otel-collector-config.yml:ro
    ports:
      - "4317:4317"
    depends_on:
      - apm-server
    networks:
      - otel-collector
      - apm
      - others

  apm-server:
    image: docker.elastic.co/apm/apm-server:7.14.0
    container_name: apm-server
    hostname: apm-server
    depends_on:
      - elasticsearch
      - kibana
    cap_add: ["CHOWN", "DAC_OVERRIDE", "SETGID", "SETUID"]
    cap_drop: ["ALL"]
    ports:
    - 8200:8200
    command: >
       apm-server -e
         -E apm-server.rum.enabled=true
         -E setup.kibana.host=kibana:5601
         -E setup.template.settings.index.number_of_replicas=0
         -E apm-server.kibana.enabled=true
         -E apm-server.kibana.host=kibana:5601
         -E output.elasticsearch.hosts=["elasticsearch:9200"]
    healthcheck:
      interval: 10s
      retries: 20
      test: curl --write-out 'HTTP %{http_code}' --fail --silent --output /dev/null http://localhost:8200/
    networks:
      - apm
      - elk

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.0
    container_name: elasticsearch
    environment:
    - node.name=es01
    - bootstrap.memory_lock=true
    - cluster.name=docker-cluster
    - discovery.type=single-node
    - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ulimits:
      memlock:
        hard: -1
        soft: -1
    ports:
    - 9200:9200
    healthcheck:
      interval: 10s
      retries: 20
      test: curl -s http://localhost:9200/_cluster/health | grep -vq '"status":"red"'
    networks:    
      - elk

  kibana:
    image: docker.elastic.co/kibana/kibana:7.14.0
    container_name: kibana
    depends_on:
      - elasticsearch
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ports:
    - 5601:5601
    healthcheck:
      interval: 10s
      retries: 20
      test: curl --write-out 'HTTP %{http_code}' --fail --silent --output /dev/null http://localhost:5601/api/status
    networks:    
      - elk

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=9411
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686 #web-port
      - 4316:4317
      - 4318:4318
      - 14250:14250
      - 14268:14268
      - 14269:14269
      - 9411:9411
    networks:
      - others

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - 9412:9411
    networks:
      - others