receivers:
  # zipkin:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch: 
    timeout: 10s

exporters:
  logging:
    logLevel: debug
    
  # zipkin:
  #   endpoint: "http://zipkin:9411/api/v2/spans"

  otlp/elastic:
    endpoint: apm-server:8200
    insecure: true

extensions:
  health_check:

service:
  extensions: [health_check]

  pipelines:
  
    # metrics:
    #   receivers: [ otlp ]

    traces:
      # receivers: [ zipkin, otlp ]
      receivers: [ otlp ]
      processors: [ batch ]
      # exporters: [ logging, zipkin, otlp/elastic ]
      exporters: [ logging, otlp/elastic ]
