receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch: 
    timeout: 10s

exporters:
  logging:
    logLevel: debug

  otlp/elastic:
    endpoint: apm-server:8200
    insecure: true

extensions:
  health_check:

service:
  extensions: [health_check]

  pipelines:
    traces:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ logging, otlp/elastic ]
    metrics:
      receivers: [otlp]
      exporters: [logging, otlp/elastic]
