version: '3.4'

services:
  entrypoint:
    image: lele-sevico-exemplo:v1.0.0
    container_name: entrypoint
    build:
      context: ./Exemplo5_Aspnet_ELK
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    environment:
      - Options__ServiceName=Entrypoint
      - Options__Mode=CLIENT
      - Options__MaxDelayMileseconds=800
      - Options__UrlClient=http://servico-core-a:5000
      - Options__OtelUrl=http://otel-collector:4317
      - Options__Jaeger__Url=jaeger
      - Options__Jaeger__Port=6831
      - Options__Zipkin__Url=http://zipkin
      - Options__Zipkin__Port=9411

  servico-core-a:
    image: lele-sevico-exemplo:v1.0.0
    container_name: servico_core_a
    environment:
      - Options__ServiceName=Servico_A
      - Options__Mode=CLIENT
      - Options__MaxDelayMileseconds=1000
      - Options__UrlClient=http://servico-core-b:5000
      - Options__OtelUrl=http://otel-collector:4317
      - Options__Jaeger__Url=jaeger
      - Options__Jaeger__Port=6831
      - Options__Zipkin__Url=http://zipkin
      - Options__Zipkin__Port=9411

  servico-core-b:
    image: lele-sevico-exemplo:v1.0.0
    container_name: servico_core_b
    environment:
      - Options__ServiceName=Servico_B
      - Options__Mode=CLIENT
      - Options__MaxDelayMileseconds=400
      - Options__UrlClient=http://servico-core-c:5000
      - Options__OtelUrl=http://otel-collector:4317
      - Options__Jaeger__Url=jaeger
      - Options__Jaeger__Port=6831
      - Options__Zipkin__Url=http://zipkin
      - Options__Zipkin__Port=9411

  servico-core-c:
    image: lele-sevico-exemplo:v1.0.0
    container_name: servico_core_c
    environment:
      - Options__ServiceName=Servico_C
      - Options__Mode=SERVER
      - Options__MaxDelayMileseconds=1800
      - Options__OtelUrl=http://otel-collector:4317
      - Options__Jaeger__Url=jaeger
      - Options__Jaeger__Port=6831
      - Options__Zipkin__Url=http://zipkin
      - Options__Zipkin__Port=9411
      - Options__Seed__Records=10
      - Options__Seed__MaxBodyWords=100

  # otel-collector:
  #   image: otel/opentelemetry-collector-contrib:0.23.0
  #   container_name: otel-collector
  #   command: ["--config=/etc/otel-collector-config.yml"]
  #   volumes:
  #     - ./config.yaml:/etc/otel-collector-config.yml:ro
  #   ports:
  #     - "4317:4317"


  # apm:   
  #   image: docker.elastic.co/apm/apm-server:7.8.1
  #   ports:
  #     - "8200:8200"
  #   command: >
  #     apm-server -e
  #              -E apm-server.rum.enabled=true
  #              -E setup.kibana.host=elk:5601
  #              -E setup.template.settings.index.number_of_replicas=0
  #              -E apm-server.kibana.enabled=true
  #              -E apm-server.kibana.host=elk:5601
  #              -E output.elasticsearch.hosts=["elk:9200"] 


  # elk:    
  #   image: sebp/elk:780
  #   ports:
  #     - "5601:5601"
  #     - "9200:9200"
  #     - "5044:5044"
  #   environment:
  #     LOGSTASH_START: 0


  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=9411
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686 #web-port
      - 4317:4317
      - 4318:4318
      - 14250:14250
      - 14268:14268
      - 14269:14269
      - 9411:9411

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - 9412:9411
